### PR TITLE
added config template

### PR DESCRIPTION
**Pull request by L11K**
Hallo! Nice bot.

I tried to set it up, but some commands doesn't work as expected, would you be able to assist me in the missing steps I must take? I am in the SDV server, you can find me there ``L-11K``.

Thanks regardless.

Edit:
```py
        embed = discord.Embed(title="**{}** Banned", description="By {}", color=0x00ff00)
        embed.add_field(name="Reason", value="{}", inline=True)
        embed.add_field(name="Time", value="[{}]", inline=False)
        await client.send_message(message.channel, embed=embed)
```
even without embed, if you format it right, stuff can be done way faster.

### CODE REVIEW

**Comment by aquova** [comment]
Hi there! 

I went ahead and added a new file, `setup.md`, which has better instructions on how to get the bot running, as well as an example `config.json` in it. I also went and removed some of the server-specific text, but some still remains, such as the DM messages sent to users.

As for the embeds, it's a nice idea and probably would be easier to read. However, we used to log everything by hand previously, so when I made the bot I had it mimic how the manual logs looked. I think we discussed switching the style, but we wanted to be consistent.

**Comment by L11K** [comment]
I see. Regardless of anything, thanks for replying, sorry for the wall of text.

I had changed the sdv parts, but do I need to do anything else? Like, the $graph command gives me instant error in the console `tkinter.TclError: no display name and no $DISPLAY environmentvariable`. 

Also, would you give me some lines about the bot actually banning/kicking instead of just logging? Because it doesn't It wasn't even checking if it had permission to ban and logging someone as banned even tho they weren't, then I realized it had not actual code to ban someone, just to log it. Like send the message that got banned and then ban the user. I'm very basic with JavaScript, so python is kind of hard for me.  

The embeds I can probably do, I just need to deal with the enum so it can work inside the embed , but the rest? Not so much. I really liked your bot, It has everything I was looking for and more, I just need small modifications.

If it's too bothersome for you, disregard this. I just thought I wouldn't know unless I asked.

It's my birthday today, so I could try to get an $10 amazon gift card to thank you for the changes I need if that would help in any way for the time you may use to do it.

**Comment by aquova** [comment]
I've just made an update that should fix $graph and have it work properly for you. Let me know if it doesn't work. You can also DM me on Discord.

If you wanted to have the bot actually ban/kick people, all you would need to do is call `await ban(user.getMember())` or `await kick(user.getMember())` somewhere in `logUser`. Line 183 would probably be a good place, but I haven't tried it. You also need to make sure that the bot has the right permissions.

And happy birthday! Please, keep your money, I couldn't accept it haha.

**Comment by L11K** [comment]
Thanks. No dice tho. I will contact you on Discord if you say you are ok with it.

**Pull request closed without merging**
